[package]
name = "fst-native"
version = "0.2.0"
edition = "2021"
authors = ["Kevin Laeufer <laeufer@berkeley.edu>"]
description = "FST wavedump format reader implemented in safe Rust."
homepage = "https://github.com/ekiwi/fst-native"
license = "BSD-3-Clause"
include = ["Cargo.toml", "LICENSE", "src/"]
keywords = ["fst", "waveform", "wavedump"]

[dependencies]
bitvec = "1"
lz4_flex = "0.11.1"
flate2 = "1.0"
num_enum = "0.7.0"
tempfile = "3"

[dev-dependencies]
fst-sys = "0.2.0"
