[package]
name = "fst-native"
version = "0.1.1"
edition = "2021"
authors = ["Kevin Laeufer <laeufer@berkeley.edu>"]
description = "FST wavedump format reader implemented in safe Rust."
homepage = "https://github.com/ekiwi/fst-native"
license = "BSD-3-Clause"
include = ["Cargo.toml", "LICENSE", "src/"]
keywords = ["fst", "waveform", "wavedump"]

[dependencies]
bitvec = "1"
lz4_flex = "0.11.1"
miniz_oxide = "0.7.1"
num_enum = "0.7.0"
